apiVersion: v1
kind: Secret
metadata:
  name: docker-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: docker
  url: registry-1.docker.io
  enableOCI: "true"
  type: helm
  username: "CHANGEME"
  password: "CHANGEME"
  ForceHttpBasicAuth: "true"