apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: wordpress-secrets
  namespace: wordpress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  target:
    name: wordpress-secrets
  data:
    - secretKey: rootPassword
      remoteRef:
        key: "secret/wordpress"
        property: "wpRootPassword"
    - secretKey: mdbPassword
      remoteRef:
        key: "secret/wordpress"
        property: "mdbPassword"
    - secretKey: mdbRootPassword
      remoteRef:
        key: "secret/wordpress"
        property: "mdbRootPassword"
