apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-external-secrets-management
  namespace: wordpress
spec:
  project: "foundation" 
  source:
    repoURL: 'https://github.com/Kcorb95/argocd-bootstrap.git'
    targetRevision: HEAD
    path: 'manifests/kubernetes'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true