apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-resources-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Kcorb95/argocd-bootstrap.git
        revision: main
        files:
          - path: "applications/kubernetes/*.yaml"
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-{{component}}"
    spec:
      project: "foundation"
      source:
        repoURL: "{{repoURL}}"
        targetRevision: "{{revision}}"
        path: "{{path}}"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
