apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-resources-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Kcorb95/argocd-bootstrap.git
              revision: main
              files:
                - path: "applications/kubernetes/*.yaml"
          - clusters: {}
  template:
    metadata:
      name: "{{name}}-{{metadata.name}}"
    spec:
      project: "foundation"
      source:
        repoURL: https://github.com/Kcorb95/argocd-bootstrap.git
        targetRevision: main
        path: applications/kubernetes
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
