apiVersion: v1
kind: Secret
metadata:
  name: bitnamicharts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnamicharts
  url: registry-1.docker.io/bitnamicharts
  enableOCI: "true"
  type: helm
#  username: "<my-oci-repo-username>"
#  password: "<my-oci-repo-pat>"
  ForceHttpBasicAuth: "true"